#! /usr/bin/env python
# encoding: utf-8


solvers = ['minisat', 'minisatp', 'glucose', 'lingeling', 'plingeling']

def options(opt):
    opt.recurse(solvers)
     
def configure(conf):
    conf.recurse(solvers)
     
def build(bld):
    bld.recurse(solvers)    

def distclean(ctx):
    ctx.recurse(solvers)  

