#! /usr/bin/env python
# encoding: utf-8

import shutil, subprocess, os

LINGELING = 'lingeling-ayv-86bf266-140429'

def options(opt):
    opt.load('compiler_c')
    opt.load('java')

def configure(conf):
    conf.load('compiler_c')
    conf.load('java')
    conf.check_jni_headers()
    sourceclean(conf)
    root = conf.path.abspath()
    subprocess.check_call(['wget', 'http://fmv.jku.at/lingeling/' + LINGELING + '.zip', '--directory-prefix', root])
    subprocess.check_call(['tar', '-xzf', root + '/' + LINGELING + '.zip', '-C', root, 'code'])

def build(bld):
    DEFINES = ['NDBLSCR', 'NLGLOG','NDEBUG', 'NCHKSOL', 'NLGLPICOSAT', 'NLGLDRUPLIG', 'NLGLYALSAT']
    CFLAGS = ['-w', '-O3', '-fPIC']
    INCLUDES = ['.']
    
    bld.objects(source = 'code/lglib.c',
                target = 'lglib',
                includes = INCLUDES, cflags = CFLAGS, defines = DEFINES)
    
    bld.shlib(source = 'kodkod_engine_satlab_Lingeling.c',
              target = 'lingeling',
              use = 'lglib', uselib = 'JAVA',
              includes = INCLUDES, cflags = CFLAGS, defines = DEFINES)

def distclean(ctx):
    from waflib import Scripting
    Scripting.distclean(ctx)
    sourceclean(ctx)

def sourceclean(ctx):
    shutil.rmtree(ctx.path.abspath() + '/code', True)
    try:
        os.remove(ctx.path.abspath() + '/' + LINGELING + '.zip')
    except OSError:
        pass
