#! /usr/bin/env python
# encoding: utf-8

import shutil
import subprocess

def options(opt):
    opt.load('compiler_cxx')
    opt.load('java')

def configure(conf):
    conf.load('compiler_cxx')
    conf.load('java')
    conf.check_jni_headers()
    conf.env.INCLUDES = ['.']
    conf.env.CXXFLAGS = [ '-w', '-O3', '-ffloat-store' ]
    conf.env.CORE_SRC = 'minisatp/*.C'
    conf.env.CORE_EXCL = 'minisatp/Main.C'
    conf.env.JNI_SRC = '*.cpp'
    MINISAT = conf.path.abspath() + '/minisatp'
    shutil.rmtree(MINISAT, True)
    subprocess.check_call(['git', 'clone', 'https://github.com/emina/minisatp.git', MINISAT])
 
def build(bld):
    bld.objects(source = bld.path.ant_glob(bld.env.CORE_SRC, excl = [bld.env.CORE_EXCL]), target = 'core')   
    bld.shlib(source = bld.path.ant_glob(bld.env.JNI_SRC), uselib = 'JAVA', use = 'core', target = 'minisatprover')


def distclean(ctx):
    from waflib import Scripting
    Scripting.distclean(ctx)
    shutil.rmtree(ctx.path.abspath() + '/minisatp', True)
    

    
    
